<a href="https://colab.research.google.com/github/mgogelr/oxford_worshop_mgogel/blob/Personal/Data_Cleaning_LSOAs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
library(tidyverse)
library(dplyr)
library(readr)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Warning message in install.packages("readr"):
“installation of package ‘readr’ had non-zero exit status”
── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.1     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.3     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
#load population
lsoa_pop <-read_csv(
  "/content/LSOA_population.csv",
  skip=6
  )
lsoa_pop <- lsoa_pop[-1,]
lsoa_pop <- lsoa_pop[1:(nrow(lsoa_pop)-5), ]

Rows: 4771 Columns: 6
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): 2001 super output areas - lower layer, mnemonic
dbl (4): row, All people, Area (hectares), 2001 Density(number of people per...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [3]:
#load tenure
lsoa_tenure <- read_csv(
  "/content/LSOA_Tenure_London.csv",
  skip = 6
)
lsoa_tenure <- lsoa_tenure[-1,]
lsoa_tenure <- lsoa_tenure[1:(nrow(lsoa_tenure)-5), ]
head(lsoa_tenure)

Rows: 4771 Columns: 10
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): 2001 super output areas - lower layer, mnemonic
dbl (8): row, Owned outright, Owned with a mortgage or loan, Shared ownershi...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  2001 super output areas - lower layer mnemonic  row Owned outright
1 Camden 001A                           E01000907 1    8.1
2 Camden 001B                           E01000908 2    8.4
3 Camden 001C                           E01000909 3   31.5
4 Camden 001D                           E01000912 4   10.9
5 Camden 001E                           E01000913 5   42.0
6 Camden 002E                           E01000899 6   37.4
  Owned with a mortgage or loan Shared ownership
1 21.5                          0.0
2 17.5                          0.3
3 30.0                          0.5
4 19.4                          2.0
5 30.4                          0.5
6 24.9                          0.0
  Rented from council(local authority)
1 51.9
2 63.3
3 16.5
4 40.6
5  5.6
6  2.4
  Rented from a housing association/registered social landlord
1  3.7
2  2.3
3  5.1
4 13.9
5  0.5
6  3.5
  Rented from a private landlord or letting agency Other
1 12.4                                             2.4
2  6.1                                             2.1
3 13.6                                             2.9
4 10.2                                             3.0
5 14.7                                             6.4
6 26.3                                             5.5

In [4]:
#load disability
lsoa_disability <- read_csv(
  "/content/LSOA_Disability_London.csv",
  skip=6
)
lsoa_disability <- lsoa_disability[1:(nrow(lsoa_disability)-3), ]

Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Rows: 4768 Columns: 6
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): 2001 super output areas - lower layer, mnemonic
dbl (4): row, All people, People with limiting long-term illness, People of ...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [5]:
#load health
lsoa_health <- read_csv(
  "/content/LSOA_Health_London.csv",
  skip = 6
)
lsoa_health <- lsoa_health[-1,]
lsoa_health <- lsoa_health[1:(nrow(lsoa_health)-5), ]

Rows: 4771 Columns: 6
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): 2001 super output areas - lower layer, mnemonic
dbl (4): row, People whose health was good, People whose health was fairly g...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [6]:
#load Ns-Sec
lsoa_Ns_SeC <- read_csv(
  "/content/LSOA_NS_SeC_London.csv",
  skip=6
)
lsoa_Ns_SeC <- lsoa_Ns_SeC[1:(nrow(lsoa_Ns_SeC)-3), ]

Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Rows: 4768 Columns: 15
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (2): 2001 super output areas - lower layer, mnemonic
dbl (13): row, Large employers and higher managerial and administrative occu...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [7]:
#load hours worked
lsoa_hours_worked <- read_csv(
  "/content/LSOA_Hours_Worked_London.csv",
  skip=6
  )
lsoa_hours_worked <- lsoa_hours_worked[1:(nrow(lsoa_hours_worked)-3), ]
nrow(lsoa_hours_worked)

Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Rows: 4768 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): 2001 super output areas - lower layer, mnemonic
dbl (3): row, Male - Mean hours worked, Female - Mean hours worked

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

[1] 4765

In [8]:
#economic activity
lsoa_econ_act <- read_csv("/content/LSOA_Economic_Activity_London.csv",
                          skip = 6

)
lsoa_econ_act <- lsoa_econ_act[-1,]
lsoa_econ_act <- lsoa_econ_act[1:(nrow(lsoa_econ_act)-5), ]
nrow(lsoa_econ_act)

Rows: 4771 Columns: 9
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): 2001 super output areas - lower layer, mnemonic
dbl (7): row, Economically active, Economically Inactive, Unemployed: Age 16...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

[1] 4765

In [9]:
#data qualifcation
lsoa_qaulifcation <- read_csv(
  "/content/LSOA_Qualification_London.csv",
  skip=6
)
lsoa_qaulifcation <- lsoa_qaulifcation[-1,]
lsoa_qaulifcation <- lsoa_qaulifcation[1:(nrow(lsoa_qaulifcation)-5), ]
nrow(lsoa_qaulifcation)

Rows: 4771 Columns: 10
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): 2001 super output areas - lower layer, mnemonic
dbl (8): row, All people aged 16-74, No qualifications, Highest level of qua...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

[1] 4765

In [11]:
#combine
lsoa_all <- lsoa_pop %>%
  left_join(lsoa_tenure, by = c("2001 super output areas - lower layer","mnemonic","row")) %>%
  left_join(lsoa_disability, by = c("2001 super output areas - lower layer","mnemonic","row")) %>%
  left_join(lsoa_health, by = c("2001 super output areas - lower layer","mnemonic","row")) %>%
  left_join(lsoa_Ns_SeC, by = c("2001 super output areas - lower layer","mnemonic","row")) %>%
  left_join(lsoa_hours_worked, by = c("2001 super output areas - lower layer","mnemonic","row")) %>%
  left_join(lsoa_econ_act, by = c("2001 super output areas - lower layer","mnemonic","row")) %>%
  left_join(lsoa_qaulifcation, by = c("2001 super output areas - lower layer","mnemonic","row"))

  2001 super output areas - lower layer mnemonic  row All people.x
1 Camden 001A                           E01000907 1   1411
2 Camden 001B                           E01000908 2   1477
3 Camden 001C                           E01000909 3   1496
4 Camden 001D                           E01000912 4   1640
5 Camden 001E                           E01000913 5   1509
6 Camden 002E                           E01000899 6   1590
  Area (hectares) 2001 Density(number of people per hectare) Owned outright
1  11             131.62                                      8.1
2  18              84.40                                      8.4
3  23              65.44                                     31.5
4  90              18.30                                     10.9
5 162               9.33                                     42.0
6 108              14.69                                     37.4
  Owned with a mortgage or loan Shared ownership
1 21.5                          0.0
2 17.5                          0.3
3 30.0                          0.5
4 19.4                          2.0
5 30.4                          0.5
6 24.9                          0.0
  Rented from council(local authority) ⋯ Unemployed: Age 50 to 74
1 51.9                                 ⋯ 1.4
2 63.3                                 ⋯ 0.8
3 16.5                                 ⋯ 0.6
4 40.6                                 ⋯ 1.2
5  5.6                                 ⋯ 0.5
6  2.4                                 ⋯ 0.8
  Unemployed: Never worked Long-term unemployed.y All people aged 16-74
1 1.0                      3.4                    100
2 0.6                      1.6                    100
3 0.3                      1.0                    100
4 0.6                      1.3                    100
5 0.3                      0.5                    100
6 0.0                      0.6                    100
  No qualifications Highest level of qualification: Level 1 qualifications
1 25.2               9.9
2 19.7              11.8
3 10.4               6.2
4 23.5              10.0
5  7.7               5.6
6  8.2               3.5
  Highest level of qualification: Level 2 qualifications
1 13.1
2 13.6
3 12.8
4 14.4
5 13.2
6 12.0
  Highest level of qualification: Level 3 qualifications
1  7.9
2 11.0
3  9.8
4  7.1
5  9.4
6 11.3
  Highest level of qualification: Level 4 qualifications and above
1 39.3
2 40.3
3 57.8
4 41.2
5 61.5
6 62.5
  Highest level of qualification: Other qualifications
1 4.5
2 3.6
3 3.1
4 3.8
5 2.5
6 2.5

[1] 46

In [24]:
lsoa_all <- lsoa_all %>%
  mutate(
    borough_name = sub(" \\d{3}[A-Z]$", "", `2001 super output areas - lower layer`)
  )

  ncol(lsoa_all)


  inner_lodnon <- c("Camden", "Hackney", "Hammersmith and Fulham", "Haringey", "Islington",
  "Kensington and Chelsea", "Lambeth", "Lewisham", "Newham",
  "Southwark", "Tower Hamlets", "Wandsworth", "Westminster")

  lsoa_all$inner_london_T <- lsoa_all$borough_name %in% inner_lodnon

[1] 48

  2001 super output areas - lower layer mnemonic  row All people.x
1 Camden 001A                           E01000907 1   1411
2 Camden 001B                           E01000908 2   1477
3 Camden 001C                           E01000909 3   1496
4 Camden 001D                           E01000912 4   1640
5 Camden 001E                           E01000913 5   1509
6 Camden 002E                           E01000899 6   1590
  Area (hectares) 2001 Density(number of people per hectare) Owned outright
1  11             131.62                                      8.1
2  18              84.40                                      8.4
3  23              65.44                                     31.5
4  90              18.30                                     10.9
5 162               9.33                                     42.0
6 108              14.69                                     37.4
  Owned with a mortgage or loan Shared ownership
1 21.5                          0.0
2 17.5                          0.3
3 30.0                          0.5
4 19.4                          2.0
5 30.4                          0.5
6 24.9                          0.0
  Rented from council(local authority) ⋯ Long-term unemployed.y
1 51.9                                 ⋯ 3.4
2 63.3                                 ⋯ 1.6
3 16.5                                 ⋯ 1.0
4 40.6                                 ⋯ 1.3
5  5.6                                 ⋯ 0.5
6  2.4                                 ⋯ 0.6
  All people aged 16-74 No qualifications
1 100                   25.2
2 100                   19.7
3 100                   10.4
4 100                   23.5
5 100                    7.7
6 100                    8.2
  Highest level of qualification: Level 1 qualifications
1  9.9
2 11.8
3  6.2
4 10.0
5  5.6
6  3.5
  Highest level of qualification: Level 2 qualifications
1 13.1
2 13.6
3 12.8
4 14.4
5 13.2
6 12.0
  Highest level of qualification: Level 3 qualifications
1  7.9
2 11.0
3  9.8
4  7.1
5  9.4
6 11.3
  Highest level of qualification: Level 4 qualifications and above
1 39.3
2 40.3
3 57.8
4 41.2
5 61.5
6 62.5
  Highest level of qualification: Other qualifications borough_name
1 4.5                                                  Camden
2 3.6                                                  Camden
3 3.1                                                  Camden
4 3.8                                                  Camden
5 2.5                                                  Camden
6 2.5                                                  Camden
  inner_london_T
1 TRUE
2 TRUE
3 TRUE
4 TRUE
5 TRUE
6 TRUE

In [25]:
#export

write.csv(lsoa_all, "lsoa_all.csv")